### ISSUE TITLE
[Scala] Release fury scala to maven snapshot

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury#1078]
## Is your feature request related to a problem? Please describe.

Release fury scala 2/3 jar to sonatype maven snapshot.

Do we need to release two jar? Or just one jar is enough?

**Comment by pjfanning** [comment]
you will need to release separate jars for Scala 3 and Scala 2.13. `sbt +publishSigned` will publish jars for all the support `crossScalaVersions` listed in the build.sbt.

**Comment by chaokunyang** [comment]
I see, thanks, I'll try it when I have time
