### ISSUE TITLE
[Java] Add serializer for Redisson

### ISSUE THREAD

**Issue by shangwq** [apache/fury#1169]
1. Can we provide Redisson serializer?
2. When I upgrade fury from 0.1.0 to latest version, I can't deserialize the data serialized by 0.1.0 version of fury using  fury of latest version,  it will throw NullPointerException exception.

**Comment by chaokunyang** [comment]
@shangwq For question2, there is an open issue for it: #919, we do not provide binary compatibility for now, you need a wrapper to load multiple fury of different version for compatibility like described in #919
