### ISSUE TITLE
[Scala] Expose register on ThreadSafeFury

### ISSUE THREAD

**Issue by ghostdogpr** [apache/fury#1186]
## Is your feature request related to a problem? Please describe.
The Scala docs say:
> If you use shared fury instance across multiple threads, you should create ThreadSafeFury instead by FuryBuilder#buildThreadSafeFury() instead.

But also:
> Otherwise if you serialize some scala types such as collection/Enumeration, you will need to register some scala internal types:
>
> ```
> fury.register(Class.forName("scala.collection.generic.DefaultSerializationProxy"))
> fury.register(Class.forName("scala.Enumeration.Val"))
> ```

However `register` is only available on `Fury`, not on `ThreadSafeFury`.

## Describe the solution you'd like
How to use `register` with `ThreadSafeFury`? It looks like it should be exposed?

**Comment by mof-dev-3** [comment]
![企业微信截图_17014323082554](https://github.com/alipay/fury/assets/129163631/7098430f-6fa7-41e9-afc8-bf9a58445c62)
One work around is to use this api    <R> R execute(Function<Fury, R> action);
I think it is accepct in this case, and fury is exposed as expected
`  @Test
  public void test() {
    ThreadSafeFury fury = Fury.builder().requireClassRegistration(false).buildThreadSafeFury();
    fury.execute(f -> {
      f.register(String.class);
      return null;
    });
  }`

**Comment by chaokunyang** [comment]
> ![企业微信截图_17014323082554](https://private-user-images.githubusercontent.com/129163631/287258936-7098430f-6fa7-41e9-afc8-bf9a58445c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MzI5ODcsIm5iZiI6MTcwMTQzMjY4NywicGF0aCI6Ii8xMjkxNjM2MzEvMjg3MjU4OTM2LTcwOTg0MzBmLTZmYTctNDFlOS1hZmM4LWJmOWE1ODQ0NWM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMjExMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODVhMWFiOGNjZTk4Y2I5YzlmMDkyMWI4YmQ2ZTliYzE4MDIzYjE4ZDU0MGIyZmJjY2VlY2RkZDVhZjE5YWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OEn4xw3MSot5FR7MuIXgMfNb2K6sVQrghADq9hIcEFM)
> One work around is to use this api R execute(Function<Fury, R> action);
> I think it is accepctable in this case, and fury is exposed as expected
> ` @Test public void test() { ThreadSafeFury fury = Fury.builder().requireClassRegistration(false).buildThreadSafeFury(); fury.execute(f -> { f.register(String.class); return null; }); }`

This is not  what this API for. Registering class here will have thread safety issue. The registration won't propagate to other threads. Maybe We should document this API to avoid such usage. 

You can create a ThreadLocalFury with fury factory instead. Then registering the classes you need.

**Comment by chaokunyang** [comment]
If you want to register on threadsafefury directly, We need to add some callback to propagate to other threads and classloaders, like we did in LoaderBinding.
