### ISSUE TITLE
[Java] Add serialization support for  java.util.ArrayList$SubList

### ISSUE THREAD

**Issue by x-wing** [apache/fury#1198]
When performing serialization with any Java object contains a List field produced by Java subList method of List, an application will get this error "java.lang.UnsupportedOperationException: Class class java.util.ArrayList$SubList doesn't support serialization."

It'd be nice to provide support for this particular serialization without resulting to create customer serialization for this standard JDK feature.

This issue can be recrreated through the following test class.
```java
import io.fury.Fury;
import io.fury.ThreadSafeFury;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class FuryTest
{
  private static final ThreadSafeFury fury = Fury.builder()
    .requireClassRegistration(false)
    .buildThreadSafeFury();

  @Test
  public void serializeAndDeserializeSubList()
  {
    List<Integer> numbers = new ArrayList<>(List.of(1, 2, 3, 4, 5));

    List<List<Integer>> partitions =
      List.of(numbers.subList(0,1), numbers.subList(1,2), numbers.subList(2, numbers.size()));

    byte[] serialized = fury.serialize(partitions);
    assertEquals(partitions, fury.deserialize(serialized));
  }
}
```

Here is the part of the stack trace:
```java
java.lang.UnsupportedOperationException: Class class java.util.ArrayList$SubList doesn't support serialization.
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:838)
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:791)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1182)
	at io.fury.resolver.ClassResolver.getClassInfo(ClassResolver.java:1081)
	at io.fury.serializer.collection.AbstractCollectionSerializer.writeTypeNullabilityHeader(AbstractCollectionSerializer.java:284)
	at io.fury.serializer.collection.AbstractCollectionSerializer.writeElementsHeader(AbstractCollectionSerializer.java:144)
	at io.fury.serializer.collection.AbstractCollectionSerializer.writeElements(AbstractCollectionSerializer.java:301)
	at io.fury.serializer.collection.AbstractCollectionSerializer.write(AbstractCollectionSerializer.java:296)
	at io.fury.Fury.writeData(Fury.java:551)
	at io.fury.Fury.writeRef(Fury.java:344)
	at io.fury.Fury.write(Fury.java:319)
	at io.fury.Fury.serialize(Fury.java:255)
	at io.fury.Fury.serialize(Fury.java:221)
	at io.fury.ThreadLocalFury.serialize(ThreadLocalFury.java:67)
```

**Comment by chaokunyang** [comment]
Hi @x-wing , thanks for filing this issue. It's a known issue. Add support for `java.util.ArrayList$SubList` is easy. Registering a customized serializer will sovle this issue. 

But it comes with new porblem. Take following example:

```java
List<String> list = new ArrayList<>();
list.add("str1");
list.add("str2");
list.add("str3");
list.add("str4");
sublist = list.subList(0, 2);

List<List<String>> newList = (List<List<String>>)(fury.deserialize(fury.serialize(Array.asList {list, sublist})));
List<String> newList0 = newList.get(0);
List<String> newList1 = newList.get(1);
```

In such cases, we'd better to serialize sublist as tow offsets and serialize parent list at the same time. Otherwise the view will be inconsistent. If we invoke sublist.set(0, "x"), then list.get(0) should be x too.

On the other hand, If we have only sublist to serialize, and we serialize by above method, we will serialize many unnecessray data outside of the range.
The point is that we can't decide whether the range is the only data to be serialized. So we didn't add serialization support for such class. And JDK doens't provide for such class too, `java.util.ArrayList$SubList` didn't implement `Serializable` interface.

If we must support such class, I would suggest serialize `Sublist` by serializing `root`, `offset` and `size`:
```java
private final ArrayList<E> root;
private final int offset;
private int size;

write(MemoryBuffer buffer, List list o) {
 buffer.writePositiveVarint(offset);
 buffer.writePositiveVarint(offset);
 fury.writeRef(buffer, o);
}
```
In this way, we may serialize extra data in some cases, but can aovid list view inconsistency between processes. And reference tracking must be enabled, otherwise the view may be inconsisitent. 

If reference tracking is disabled, you won't get consisitent view. In such cases, you just write the range of data like it just an normal ArrayList. To ensure the type is consisitent, you can overwrite `onCollectionRead` to return a `SubList`:
```java
  @Override
  public T onCollectionRead(Collection collection) {
    return (T) collection;
  }
```

**Comment by chaokunyang** [comment]
Maybe we can add some serializes in io.fury.serializer.SubListSerializers and document it in fury Java guide. Then let users to register such serializes if they need. Would you like to submit a pr?

**Comment by x-wing** [comment]
Sure, but it will take me some time to get it done as I need to learn a little more about the coding conventions here.
If a delay is OK, I will do the PR. BTW I also noticed that com.google.common.collect.HashBasedTable is not supported. Wonder if it should be created in another feature request.

**Comment by chaokunyang** [comment]
> Sure, but it will take me some time to get it done as I need to learn a little more about the coding conventions here. If a delay is OK, I will do the PR. BTW I also noticed that com.google.common.collect.HashBasedTable is not supported. Wonder if it should be created in another feature request.

@x-wing Thank you for offering to contribute with a Pull Request! Learning the coding conventions is important and it takes time, so a delay is perfectly acceptable. Please take the time you need, and let us know if you have any questions or need any guidance.

Regarding the `com.google.common.collect.HashBasedTable` support, it would be great if you could create a separate feature request for it. I can reproduce the error for `HashBasedTable`, I will fix it soon

**Comment by x-wing** [comment]
Don't know if this is the right place to ask this question. I just checked out the project and ran ` mvn -T10 clean test`.
There are some unit test failures. Any ideas?

Here are the errors
[ERROR] Failures: 
[ERROR]   CrossLanguageTest.testBuffer:135 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testCrossLanguageReference:433 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testCrossLanguageSerializer:308 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testMurmurHash3:167 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testOutOfBandBuffer:695 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testRegisterSerializer:641 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testSerializeComplexStruct:501->structRoundBack:515 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testSerializeOpaqueObject:562 expected [true] but found [false]
[ERROR]   CrossLanguageTest.testSerializeSimpleStruct:472->structRoundBack:515 expected [true] but found [false]
[INFO]
[ERROR] Tests run: 797, Failures: 9, Errors: 0, Skipped: 3

**Comment by chaokunyang** [comment]
> CrossLanguageTest.testSerializeSimpleStruct:472->structRoundBack:515 expected [true] but found [false] [INFO] [ERROR] Tests run: 797, Failures: 9, Errors: 0, Skipped: 3

Such cases needs to install `pyfury` first, you can ignore it if you don't develop cross-language features. `pyfury` can be installed by following  https://github.com/alipay/fury/blob/main/docs/guide/DEVELOPMENT.md#building-fury-python . You may need to setup gcc/clang and pyenv for install pyfury too, which may take some time.

**Comment by x-wing** [comment]
> Hi @x-wing `HashBasedTable` serialization failure has been fixed in release https://github.com/alipay/fury/releases/tag/v0.4.1 , could you try it out?

Yes, it is fixed!
