### ISSUE TITLE
[Go] Implement meta string encoding algorithm for golang

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury#1540]
## Is your feature request related to a problem? Please describe.
We've implemented  meta string encoding algorithm in https://fury.apache.org/docs/specification/fury_xlang_serialization_spec#meta-string for java in #1514   , it's time to implement it in golang.

## Describe the solution you'd like
Java implementation in #1514 can be taken as a reference. But note that the meta string encoding algorithm is used for encode field name only, so the special charater can't be `.` or `$`, thus the implementation will be simpler

## Additional context
#1413

**Comment by qingoba** [comment]
Could you assign it to me? This is my first try of open source and I'm very interested in this task. Thanks.

**Comment by chaokunyang** [comment]
Great, thanks for the willingness to contribute to Fury

**Comment by chaokunyang** [comment]
hmm, this is a bug, UTF-8 is barely used in meta string. Acutally, most chars are ascii chars. So it's not covered in Fury serialization tests. We need to fix it and add some unit tests.

Thanks for pointing out this bug @qingoba

**Comment by chaokunyang** [comment]
I have a new idea, we can add a bit to incidate whether strip last char in encoded meta string if the encoding is not UTF-8. In this way, we don't have to store num bits and num chars in MetaString

**Comment by qingoba** [comment]
I don't understand what you mean, could you give an example?
Actually, I think `numChars` can be omitted, because it can be computed by `numBits` when needed.

**Comment by qingoba** [comment]
In this way, the Decoder does not need to accept `numBits` arguments.

**Comment by chaokunyang** [comment]
> I have a new idea, we can add a bit to incidate whether strip last char in encoded meta string if the encoding is not UTF-8. In this way, we don't have to store num bits and num chars in MetaString

Hi @qingoba , I added stip last char flag to spec in #1565 . I believe this will make the implementation simpler
