### ISSUE TITLE
[JavaScript] Implement meta string encoding algorithm for JavaScript

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury#1542]
## Is your feature request related to a problem? Please describe.
We've implemented  meta string encoding algorithm in https://fury.apache.org/docs/specification/fury_xlang_serialization_spec#meta-string for java in #1514   , it's time to implement it in javascript.

## Describe the solution you'd like
Java implementation in #1514 can be taken as a reference. But note that the meta string encoding algorithm is used for encode field name only, so the special charater can't be `.` or `$`, thus the implementation will be simpler

## Additional context
#1413

**Comment by Forchapeatl** [comment]
Hello @chaokunyang  , I am Forcha Pearl from Cameroon . I am very good  bit manipulation, endianess, encoding DataStructures and Algorithm. I also experienced with Java, python and javascript.  I am interested in participting in OSPP 2024 under Apache furry this year. Please  has this issue ben reserved for the OSPP  contribution period.

**Comment by chaokunyang** [comment]
> Hello @chaokunyang , I am Forcha Pearl from Cameroon . I am very good bit manipulation, endianess, encoding DataStructures and Algorithm. I also experienced with Java, python and javascript. I am interested in participting in OSPP 2024 under Apache furry this year. Please has this issue ben reserved for the OSPP contribution period.

Hi @Forchapeatl , this is not an issue reserved for the OSPP. If it's not taken by someone else in this month, we will take it over. The issues for OSPP can be found at #1670

**Comment by theweipeng** [comment]
> Hello @chaokunyang , I am Forcha Pearl from Cameroon . I am very good bit manipulation, endianess, encoding DataStructures and Algorithm. I also experienced with Java, python and javascript. I am interested in participting in OSPP 2024 under Apache furry this year. Please has this issue ben reserved for the OSPP contribution period.

@Forchapeatl 
Hi, I am the mentor for the OSPP Fury Javascript project. Your participation is welcome. However, I noticed that the OSPP application period is about to end on June 4th at 18:00. You should submit your application on OSPP as soon as possible.

**Comment by Forchapeatl** [comment]
Thank you @theweipeng . @chaokunyang , Please  assign this issue to me. I would love to work on this

**Comment by chaokunyang** [comment]
> Thank you @theweipeng . @chaokunyang , Please assign this issue to me. I would love to work on this

Great, assigned to you

**Comment by barrerajuanjose** [comment]
Hi @chaokunyang. I would like to take care of this issue, is there someone else working on it? Thanks

**Comment by chaokunyang** [comment]
Hi @barrerajuanjose , thanks form contribuing to Fury. This has been implemented by @Forchapeatl in #1774. If you are interested at Fury, you can take other issues.
