### ISSUE TITLE
[Rust] Implement meta string encoding algorithm for rust

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury#1544]
## Is your feature request related to a problem? Please describe.
We've implemented  meta string encoding algorithm in https://fury.apache.org/docs/specification/fury_xlang_serialization_spec#meta-string for java in #1514   , it's time to implement it in rust.

## Describe the solution you'd like
Java implementation in #1514 can be taken as a reference. But note that the meta string encoding algorithm is used for encode field name only, so the special charater can't be `.` or `$`, thus the implementation will be simpler

## Additional context
#1413

**Comment by Kelvinyu1117** [comment]
I would like to try.

**Comment by chaokunyang** [comment]
> #1514

Great, thanks for the willingness to contribute to Apache Fury. Note that Java implementation in https://github.com/apache/incubator-fury/pull/1514 has some changes, please see latest code in main branch

**Comment by urlyy** [comment]
Hi！I saw this issue in the Alibaba Cloud Tianchi TONGYI Lingma competition. I would like to try implementing it.

**Comment by chaokunyang** [comment]
> Hi！I saw this issue in the Alibaba Cloud Tianchi TONGYI Lingma competition. I would like to try implementing it.

Great! thanks for contributing to Apache Fury. Seems @Kelvinyu1117 hasn't been working on this, you could take it over
