### ISSUE TITLE
Doc: Broken link on website

### ISSUE THREAD

**Issue by sebbASF** [apache/fury#1682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

NA

### Component(s)

Other

### Minimal reproduce step

https://github.com/apache/incubator-fury-site
Click README.md
Click DISCLAIMER

### What did you expect to see?

The DISCLAIMER text

### What did you see instead?

404 - page not found

### Anything Else?

This form is not really suitable for reporting issues with the website

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @sebbASF , thanks for reporting this issue, I fixed it in https://github.com/apache/incubator-fury-site/pull/129
