### ISSUE TITLE
[Java] NPE when serializing with withMetaShare

### ISSUE THREAD

**Issue by LiangliangSui** [apache/fury#1704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

main branch

### Component(s)

Java

### Minimal reproduce step

```java
public void repoduct() {
    Fury fury =
        Fury.builder()
            .withRefTracking(true)
            .requireClassRegistration(false)
            .withMetaShare(true)
            .build();
    String str = "Hello world";
    byte[] bytes = fury.serialize(str);
    Object obj = fury.deserialize(bytes);
}
```

### What did you expect to see?

Serialization and deserialization succeeded.

### What did you see instead?

```
java.lang.NullPointerException
	at org.apache.fury.resolver.ClassResolver.writeClassDefs(ClassResolver.java:1412)
	at org.apache.fury.Fury.write(Fury.java:322)
	at org.apache.fury.Fury.serialize(Fury.java:251)
	at org.apache.fury.Fury.serialize(Fury.java:205)
```

### Anything Else?

```java
  public SerializationContext(Config config) {
    scopedMetaShareEnabled = config.isScopedMetaShareEnabled();
    if (scopedMetaShareEnabled) {
      metaContext = new MetaContext();
    }
  }
```
`MetaContext` is created only when `scopedMetaShareEnabled`. We should change it to create `MetaContext` only when `withMetaShare` is enabled.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by LiangliangSui** [comment]
Could we instantiate a `MetaContext` object in the `SerializationContext constructor` with `withMetaShare` enabled, without requiring the user to manually set a `MetaContext` instance through the `SerializationContext#setMetaContext` interface?

For example, the following implementation.

```java
package org.apache.fury.resolver;

import java.util.IdentityHashMap;
import org.apache.fury.config.Config;
import org.apache.fury.config.FuryBuilder;

/**
 * A context is used to add some context-related information, so that the serializers can set up
 * relation between serializing different objects. The context will be reset after finished
 * serializing/deserializing the object tree.
 */
public final class SerializationContext {
  private final IdentityHashMap<Object, Object> objects = new IdentityHashMap<>();
  private final boolean scopedMetaShareEnabled;
  private final boolean withMetaShare;
  private MetaContext metaContext;

  public SerializationContext(Config config) {
    scopedMetaShareEnabled = config.isScopedMetaShareEnabled();
    withMetaShare = config.isMetaShareEnabled();
    if (withMetaShare) {
      metaContext = new MetaContext();
    }
  }

  /** Return the previous value associated with <tt>key</tt>, or <tt>null</tt>. */
  public Object add(Object key, Object value) {
    return objects.put(key, value);
  }

  public boolean containsKey(Object key) {
    return objects.containsKey(key);
  }

  public Object get(Object key) {
    return objects.get(key);
  }

  public MetaContext getMetaContext() {
    return metaContext;
  }

  /**
   * Set meta context, which can be used to share data across multiple serialization call. Note that
   * {@code metaContext} will be cleared after the serialization is finished. Please set the context
   * before every serialization if metaShare is enabled by {@link FuryBuilder#withMetaShare(boolean)}
   */
  public void setMetaContext(MetaContext metaContext) {
    this.metaContext = metaContext;
  }

  public void resetWrite() {
    if (!objects.isEmpty()) {
      objects.clear();
    }
    if (scopedMetaShareEnabled) {
      metaContext.classMap.clear();
      metaContext.writingClassDefs.clear();
    } else if (withMetaShare) {
      metaContext = new MetaContext();
    } else {
      metaContext = null;
    }
  }

  public void resetRead() {
    if (!objects.isEmpty()) {
      objects.clear();
    }
    if (scopedMetaShareEnabled) {
      metaContext.readClassInfos.clear();
      metaContext.readClassDefs.clear();
    } else if (withMetaShare) {
      metaContext = new MetaContext();
    } else {
      metaContext = null;
    }
  }

  public void reset() {
    if (!objects.isEmpty()) {
      objects.clear();
    }
    if (scopedMetaShareEnabled) {
      metaContext.classMap.clear();
      metaContext.writingClassDefs.clear();
      metaContext.readClassInfos.clear();
      metaContext.readClassDefs.clear();
    } else if (withMetaShare) {
      metaContext = new MetaContext();
    } else {
      metaContext = null;
    }
  }
}
```

**Comment by chaokunyang** [comment]
No, we can't. That's what scopedMetaShare option do. We will make it as the default option in the future. But the meta share itself, will always need to set MetaContext. As you can see, the NPE here is throw by fury on purpose

**Comment by LiangliangSui** [comment]
Users will not use the created MetaContext directly. What is the purpose of letting users set MetaContext through the setMetaContext interface? Is it just to let users know that MetaContext is shared between multiple serializations?

**Comment by LiangliangSui** [comment]
If we just want to let users know that MetaContext is shared between multiple serializations, can we explain this problem in the withMetaShare option?

Our goal should be to let users know that MetaContext is shared between multiple serializations, and it can be set optionally through the setMetaContext interface, rather than forcing users to set it when enabling withMetaShare.

I don't know if I understand it correctly

**Comment by chaokunyang** [comment]
I think adding a precheck in `org.apache.fury.resolver.ClassResolver#writeClassDefs` is enough. We can provide a detailed error message to indicate users need to set MetaContext here.

**Comment by chaokunyang** [comment]
> If we just want to let users know that MetaContext is shared between multiple serializations, can we explain this problem in the withMetaShare option?
> 
> Our goal should be to let users know that MetaContext is shared between multiple serializations, and it can be set optionally through the setMetaContext interface, rather than forcing users to set it when enabling withMetaShare.
> 
> I don't know if I understand it correctly

Not exactly, users will use this API directly, as you can see from the use case:
```java
  public void testSimpleRecordMetaShared(boolean codegen) {
    Fury fury =
        Fury.builder()
            .requireClassRegistration(false)
            .withCodegen(codegen)
            .withMetaShare(true)
            .build();
    Foo foo = new Foo(10, "abc", new ArrayList<>(Arrays.asList("a", "b")), 'x');
    MetaContext context = new MetaContext();
    fury.getSerializationContext().setMetaContext(context);
    byte[] bytes = fury.serialize(foo);
    fury.getSerializationContext().setMetaContext(context);
    Assert.assertEquals(fury.deserialize(bytes), foo);
  }
```

This will be used by rpc framework too reuse meta across multiple serializaition. Or used by bigdata frameworks to serialize data by batch.

**Comment by LiangliangSui** [comment]
> Not exactly, users will use this API directly, as you can see from the use case:

I mean that users will not directly use any API and data in MetaContext, but it is exposed to users.

> This will be used by rpc framework too reuse meta across multiple serializaition. Or used by bigdata frameworks to serialize data by batch.

I have another question, will MetaContext be shared across different Fury objects?

**Comment by chaokunyang** [comment]
Users will use this API:
```java
  @Test(dataProvider = "codegen")
  public void testBatch(boolean codegen) {
    Fury fury =
        Fury.builder()
            .requireClassRegistration(false)
            .withCodegen(codegen)
            .withMetaShare(true)
            .build();
    MetaContext context = new MetaContext();
    for (int i = 0; i < 10000; i++) {
      Foo foo = new Foo(10, "abc", new ArrayList<>(Arrays.asList("a", "b")), 'x');
      fury.getSerializationContext().setMetaContext(context);
      byte[] bytes = fury.serialize(foo);
      fury.getSerializationContext().setMetaContext(context);
      Assert.assertEquals(fury.deserialize(bytes), foo);
    }
  }
```

**Comment by chaokunyang** [comment]
MetaContext will be shared across different Fury objects, that's what it is used for

**Comment by LiangliangSui** [comment]
> MetaContext will be shared across different Fury objects, that's what it is used for

Ok, got it, if it is reused in different Fury objects, then we do need setMetaContext.

Thank you for helping me solve this problem. Thanks again.
