### ISSUE TITLE
default value of deserializeUnexistedClass is false when set to CompatibleMode mode

### ISSUE THREAD

**Issue by shaozhen2012** [apache/fury#1718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.4.1

### Component(s)

Java

### Minimal reproduce step

    The document states that when set to CompatibleMode mode, deserializeUnexistedClass will default to true, but it does not seem to take effect, so you need to explicitly set it.
  document:
![image](https://github.com/apache/fury/assets/13158527/869a1480-91bf-46b5-80cc-918153f7936b)

 ____

### What did you expect to see?

deserializeUnexistedClass is true when set to CompatibleMode mode

### What did you see instead?

deserializeUnexistedClass is false when set to CompatibleMode mode, you need to explicitly set it

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LiangliangSui** [comment]
Hi @shaozhen2012 , Could you try this feature in v0.5.1? We haven't introduced it in v0.4.1 yet.

**Comment by LiangliangSui** [comment]
I think we should indicate in the config options of the document which version introduced. @chaokunyang

**Comment by chaokunyang** [comment]
Would you like to update the document? @LiangliangSui

**Comment by LiangliangSui** [comment]
> Would you like to update the document? @LiangliangSui

I will update this document.
