### ISSUE TITLE
class CircularFifoQueue customized jdk serialization, which is inefficient. Please replace it with a org.apache.fury.serializer.Serializer or implements java.io.Externalizable

### ISSUE THREAD

**Issue by cdxf** [apache/fury#1721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.5.1

### Component(s)

Java

### Minimal reproduce step

Try to serialize org.apache.commons.collections4.queue.CircularFifoQueue class

### What did you expect to see?

I want more explanation why it is inefficient, will it causes memory leak, what can I do to improve this

### What did you see instead?

class org.apache.commons.collections4.queue.CircularFifoQueue customized jdk serialization, which is inefficient. Please replace it with a org.apache.fury.serializer.Serializer or implements java.io.Externalizable

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
As the warn log said, you may need to implement a Fury Serializer for CircularFifoQueue. CircularFifoQueue implements JDK writeObject/readObject method. Fury must invoke those methods to ensure compatibility. You can register a customized serializer instead to speed serialization
