### ISSUE TITLE
FR: Only serialize annotated fields

### ISSUE THREAD

**Issue by Frotty** [apache/fury#1735]
## Is your feature request related to a problem? Please describe.
I want to move an existing project to fury, but right now data fields in classes are marked with an annotation. Fury only supports not de-/serializing transient fields, but it's not convenient to mark a majority of fields as transient.

## Describe the solution you'd like
I would like there to be an annotation that allows me to mark only the fields of a class that should be de-/serialized.

## Additional context
This was discussed @chaokunyang in https://www.reddit.com/r/java/comments/1cll68f/comment/ld3suns/?context=3 and he is generally supportive. However, there seems to be no real guide for me to start implementing this. Perhaps someone else can do it in a shorter amount of time.

**Comment by urlyy** [comment]
@chaokunyang I'm interested in this issue. However , as it's my first time delving into the Java version of Fury, I'm not quite sure if my approach is correct. By using DEBUG, I've traced the code and found a method which obtains the list of fields of the object being serialized, this `descriptorMap` ultimately also participates in serializer codegen. Here is already a check on the `Ignore` annotation; I need to modify the logic.
Do you have some advice? To be honest I don't know if it's enough to modify this method , maybe I should explore more.

![image](https://github.com/user-attachments/assets/e466c7f8-dbf5-4fbc-8622-37bf4d507f14)

**Comment by Frotty** [comment]
Cool, would be nice to see this implemented. I suppose there must be a configuration or mode, or annotation on the class itself, to switch the fury behavior to only serialize marked fields. Otherwise, might be quite straightforward. Currently, the annotation is `@Exposed` but I don't really care about the name.

**Comment by chaokunyang** [comment]
The implementation should not be complex, but the naming is an issue. This is a public API, how do we name this annotation?

**Comment by Pil0tXia** [comment]
Good job. Might we consider this issue as completed?

**Comment by Frotty** [comment]
I wasn't able to test it yet, when will it be available in a release?

**Comment by chaokunyang** [comment]
> I wasn't able to test it yet, when will it be available in a release?

You can use snapshot jar for test. A release jar will be released by the end of this week
