### ISSUE TITLE
feat(java):add Ignore type inconsistent deserialize

### ISSUE THREAD

**Issue by weijiang157152688** [apache/fury#1738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.6.0

### Component(s)

Java

### Minimal reproduce step

 // type is inconsistent use serialize type, except enum

### What did you expect to see?

deserialize ok

### What did you see instead?

.

### Anything Else?

.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Finished in #1737
