### ISSUE TITLE
license issue in fury-core jar

### ISSUE THREAD

**Issue by pjfanning** [apache/fury#1745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

The META-INF/LICENSE in https://repository.apache.org/content/repositories/orgapachefury-1043/org/apache/fury/fury-core/0.6.0/fury-core-0.6.0.jar is the source license. There should be a dedicated license file for the jars.
I see that the janino and kryo licenses are included in META-INF/licenses but they should be mentioned in META-INF/LICENSE.

### Component(s)

Java

### Minimal reproduce step

n/a

### What did you expect to see?

better LICENSE in jar

### What did you see instead?

n/a

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
We have text `The text of each license is also included in licenses/LICENSE-[project].txt` in `java/fury-core/src/main/resources/META-INF/LICENSE`:
```
The following components are provided under the BSD-3-Clause License. See project link for details.
The text of each license is also included in licenses/LICENSE-[project].txt.


* kryo (https://github.com/EsotericSoftware/kryo)
    Files:
      java/fury-core/src/main/java/org/apache/fury/collection/FuryObjectMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/IdentityMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/IdentityObjectIntMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/LongMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/ObjectIntMap.java
      java/fury-core/src/main/java/org/apache/fury/type/Generics.java

* janino (https://github.com/janino-compiler/janino)
    Files:
      Shaded classes under org/apache/fury/shaded/org/codehaus/janino/*
```

Do we need to update it into specific file name in this LICENSE file?

**Comment by chaokunyang** [comment]
We have text `The text of each license is also included in licenses/LICENSE-[project].txt` in `java/fury-core/src/main/resources/META-INF/LICENSE`:
```
The following components are provided under the BSD-3-Clause License. See project link for details.
The text of each license is also included in licenses/LICENSE-[project].txt.


* kryo (https://github.com/EsotericSoftware/kryo)
    Files:
      java/fury-core/src/main/java/org/apache/fury/collection/FuryObjectMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/IdentityMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/IdentityObjectIntMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/LongMap.java
      java/fury-core/src/main/java/org/apache/fury/collection/ObjectIntMap.java
      java/fury-core/src/main/java/org/apache/fury/type/Generics.java

* janino (https://github.com/janino-compiler/janino)
    Files:
      Shaded classes under org/apache/fury/shaded/org/codehaus/janino/*
```

Do we need to update it into specific file name in this LICENSE file?

**Comment by pjfanning** [comment]
the LICENSE doesn't mention `shaded/org/codehaus/commons/` - there are classes in fury-core that are shaded versions of commons compiler classes. I guess this is part of Janino but we should update the Janino section to mention `shaded/org/codehaus/commons/`.

**Comment by chaokunyang** [comment]
I see, thanks. I will fix this soon.
