### ISSUE TITLE
[Java] Support copy capabilities for some classes without no-argument constructors

### ISSUE THREAD

**Issue by zhaommmmomo** [apache/fury#1777]
## Is your feature request related to a problem? Please describe.
Some classes with no-argument constructors will report an error when calling `copy()`

## Describe the solution you'd like
These classes can use the copy capability normally.

## Additional context
![image](https://github.com/user-attachments/assets/c7764252-ccb5-42bd-80d5-bda7e418f02e)

**Comment by zhaommmmomo** [comment]
I will deal with this issue

**Comment by zhaommmmomo** [comment]
I will deal with it. If there is anything to add, please let me know. @chaokunyang

**Comment by chaokunyang** [comment]
Would you like to submit a PR to support the copy of all guava Container?

**Comment by zhaommmmomo** [comment]
> Would you like to submit a PR to support the copy of all guava Container?

yes
