### ISSUE TITLE
Fury FAQ

### ISSUE THREAD

**Issue by LofiSu** [apache/fury#1793]
# Apache Fury 
### **Apache Fury  ── A blazing-fast cross-language serialization framework powered by just-in-time compilation and zero-copy !**
>  # FAQ

**Comment by chaokunyang** [comment]
If uses have some issues, they should create it in https://github.com/apache/fury/issues instead of here. Do we really need this issue?

**Comment by LofiSu** [comment]
> If uses have some issues, they should create it in https://github.com/apache/fury/issues instead of here. Do we really need this issue?

I'm not sure about this, but it seems that almost all communities have FAQ links. Maybe we can shrink the font size of the navigation bar a bit and leave room for the “Team” and “Users” pages.I think it is more important to fill in the content now. At present, the home page is empty and needs to be filled with more introductions and content.

**Comment by chaokunyang** [comment]
Maybe it should be a page like https://arrow.apache.org/faq/ rather an issue?

**Comment by LofiSu** [comment]
> Maybe it should be a page like https://arrow.apache.org/faq/ rather than an issue?

This is a much better choice.

**Comment by chaokunyang** [comment]
I will close this issue, we can open a new issue to add a new FAQ page. But more importantly, we need to decide what should be included here
