### ISSUE TITLE
[Java] Add support for deserialization between applications and use of typeTag on thread safe instances

### ISSUE THREAD

**Issue by rvcoutinho** [apache/fury#1796]
I have been using Fury as a mean for serialization in a single application. When it comes to move serialized objects between applications, I have not been able to deal with different DTO packages/classNames (different origin and target classes).

I have tried using XLANG serialization and registering classes with the same typeTag, but it does not work. My understanding is that it should work similarly to a cross language de-serialization. 

As an additional comment, the typeTag registration is not available on thread safe classes in Java (not defined on BaseFury). I don't see a reason why not to have the option on thread safe usages.

**Comment by rvcoutinho** [comment]
In fact, it looks likea bug. If I serialize an object using XLANG, and then try to deserialize it, I get an error: Index out of bounds (regardless of de-serializing to the same class).

**Comment by chaokunyang** [comment]
Type tag was designed for xlang serialization. But you come up with a good use scenario. We should extend type tag to support Java serialization. After it's supported, We should add this to BaseFury interface.
