### ISSUE TITLE
Scala: wrong class name in generated java source for class inside nested objects

### ISSUE THREAD

**Issue by yoohaemin** [apache/fury#1801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.7.0

### Component(s)

Java, Other

### Minimal reproduce step

https://github.com/yoohaemin/fury-bugreport/blob/65788b6902939e71aa136959183c13b132861ce6/src/main/scala/Main.scala

You can clone the repo and try `sbt run` at the root of the repo.

### What did you expect to see?

serialization round-trip works

### What did you see instead?

generate java source failed to compile. See the linked file above for the message.

### Anything Else?

See: https://stackoverflow.com/questions/30809070/accessing-scala-nested-classes-from-java

This shows the correct format of referring to classes inside nested scala `object`s. In this case, it should be `test.A$B$C`. It generated `test.A.B$.C` (See line 40 of the generated code inside my example).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yoohaemin** [comment]
I wonder if it's possible to fallback to disabling jit when code compilation fails, instead of failing.
We get performance penalty but at least it will work correctly.

**Comment by chaokunyang** [comment]
Disabling jit at runtime may swallow some errors. The codegen error is limitted. I believe we can fix this soon

**Comment by chaokunyang** [comment]
You can workaroung this by register ObjectSerializer for this type

**Comment by chaokunyang** [comment]
Hi @yoohaemin , I fixed this issue in #1809, please take a look

**Comment by yoohaemin** [comment]
@chaokunyang Thank you very much, I was able to verify the issue does not appear on 0.8.0-SNAPSHOT
