### ISSUE TITLE
How to save/load and where is save file location?

### ISSUE THREAD

**Issue by Xeaker** [apache/fury#1808]
Hi, I want to save every variable in my Data Class. How do I do it? I tried this from the instruction post.
```
               fury = Fury.builder().withLanguage(Language.JAVA)
                  .requireClassRegistration(true)
                  .build();
                fury.register(Data.class);
                fury.register(Hexagon.class);
                fury.register(Vector3.class);
                fury.register(Units.class);
                fury.register(Array.class);
                fury.register(FactionList.class);
                fury.register(Point.class);
                byte[] bytes = fury.serialize(data);
                System.out.println(fury.deserialize(bytes));
```

But how do I load them back? With JSON I do this:
```
//Saving
serializedInts = json.toJson(data); 
prefs.putString("data", serializedInts); 
prefs.flush();       
//Loading
serializedInts = prefs.getString("data","No Array stored"); 
data=json.fromJson(Data.class,serializedInts);        
```

Also where is the save file located?

**Comment by chaokunyang** [comment]
What do you mean load back? You can just cast the deserialized object into your type:
```java
Point  p = (Point) fury.deserialize(bytes);
```

**Comment by Xeaker** [comment]
> What do you mean load back? You can just cast the deserialized object into your type:
> 
> ```java
> Point  p = (Point) fury.deserialize(bytes);
> ```

But where is the save file located? If I close my game and restart it, how can I load the saved data with fury?

**Comment by chaokunyang** [comment]
This is not related to Fury, you can save the serialized bytes to file by yourself

**Comment by Xeaker** [comment]
Ok, I will try in libgdx forum. Thanks.
