### ISSUE TITLE
[Question] Can you reduce file size somehow?

### ISSUE THREAD

**Issue by Xeaker** [apache/fury#1815]
### Question

Hi, my save file with fury is twice as big as with JSON. Is there a way to reduce it? That's how I do it:

![fury](https://github.com/user-attachments/assets/b3fc7dd9-7ecf-44c3-9b27-48eed7547b9c)

And then:
 
![fur2](https://github.com/user-attachments/assets/ff2ce668-99a5-413a-bab5-0813d644ffbd)

**Comment by chaokunyang** [comment]
You convert a binary into string, maybe that is why size got bigger. And could you provide the reproduction code? It's not possible to find out what happened if we have just a screencut

**Comment by Xeaker** [comment]
> You convert a binary into string, maybe that is why size got bigger. And could you provide the reproduction code? It's not possible to find out what happened if we have just a screencut

What is reproduction code? Do you need the save files?
I can't send you my project it's a huge game.

**Comment by chaokunyang** [comment]
> > You convert a binary into string, maybe that is why size got bigger. And could you provide the reproduction code? It's not possible to find out what happened if we have just a screencut
> 
> What is reproduction code? Do you need the save files? I can't send you my project it's a huge game.

I need the code which can produce larger binary than json locally. Then we can start to figure out what happened. 

To be honest, fury serialized binary is far smaller than json. We never came across a situation which the produced binary is bigger

**Comment by Xeaker** [comment]
> I need the code which can produce larger binary than json locally. Then we can start to figure out what happened.

I saved the file now as .bin instead of .txt and it is now a little smaller than with JSON. Thanks!
