### ISSUE TITLE
create sequential serializer failed

### ISSUE THREAD

**Issue by KayLi1021** [apache/fury#1816]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.7.0

### Component(s)

Java

### Minimal reproduce step

我们是在javaAgent实现的mock和流量采集插件中使用fury的，在拦截到目标方法的返回值时，用fury序列化，报错create sequential serializer failed，代码如下
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/0712ee36-1047-4275-8ed8-bb19415e2a63">

### What did you expect to see?

正确序列化

### What did you see instead?

<img width="1572" alt="image" src="https://github.com/user-attachments/assets/f9c133e9-9fcf-4f6a-bcd6-61cd783af04c">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Could you provide reproduction code here
