### ISSUE TITLE
How to register a non-public class

### ISSUE THREAD

**Issue by Kn0688** [apache/fury#1824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

fury: 0.7.0

### Component(s)

Java

### Minimal reproduce step

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/3afc1f42-f892-448b-b19a-74b83200fc5d">
full name: com.google.protobuf.LongArrayList
The proto buffer object shown in the above figure

### What did you expect to see?

register non-public class

### What did you see instead?

register non-public class

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
You could use reflection like `fury.register(Class.forName)`

**Comment by Kn0688** [comment]
ok
