### ISSUE TITLE
[Java] CPU Utilization 100%

### ISSUE THREAD

**Issue by eryanwcp** [apache/fury#1840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.7.0

### code

public class FurySerializer implements Serializer {

    private final ThreadSafeFury fury;

    public FurySerializer(){
        LoggerFactory.useSlf4jLogging(true);
        this.fury = Fury.builder().withLanguage(Language.JAVA)
                // Allow to deserialize objects unknown types, more flexible
                // but may be insecure if the classes contains malicious code.
                .withRefTracking(true)
                .requireClassRegistration(false)
                .buildThreadSafeFury();
    }

    @Override
    public String name() {
        return "fury";
    }

    @Override
    public byte[] serialize(Object obj) throws IOException {
        return fury.serialize(obj);
    }

    @Override
    public Object deserialize(byte[] bytes) throws IOException {
        return fury.deserialize(bytes);
    }

}

### 出现大量线程CPU100%，异常：

  at java.util.WeakHashMap.put(java.base@17.0.12/WeakHashMap.java:459)
        at org.apache.fury.ThreadLocalFury.lambda$new$2(ThreadLocalFury.java:60)
        at org.apache.fury.ThreadLocalFury$$Lambda$1294/0x00007f9fb0bcd7e8.get(Unknown Source)
        at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(java.base@17.0.12/ThreadLocal.java:305)
        at java.lang.ThreadLocal.setInitialValue(java.base@17.0.12/ThreadLocal.java:195)
        at java.lang.ThreadLocal.get(java.base@17.0.12/ThreadLocal.java:172)
        at org.apache.fury.ThreadLocalFury.deserialize(ThreadLocalFury.java:130)
        at com.eryansky.j2cache.util.FurySerializer.deserialize(FurySerializer.java:40)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
@eryanwcp Do you create too much Fury instance? As the document cleared: 
![image](https://github.com/user-attachments/assets/39df0219-1b7b-4af8-a12b-a4948f75eaa5)

**Comment by chaokunyang** [comment]
Could you use `ThreadPoolFury` instead? Seems you created too much threads, and every thread will create a new Fury instance

**Comment by eryanwcp** [comment]
@chaokunyang Only One Fury instance. 

Spring Boot 3.3+[dragonwell](https://github.com/dragonwell-project/dragonwell17)

https://github.com/eryanwcp/ec/blob/master/j2cache-spring-boot-starter/src/main/java/com/eryansky/j2cache/cache/support/util/J2CacheSerializer.java

**Comment by chaokunyang** [comment]
`private final ThreadSafeFury fury;` should be `private final static ThreadSafeFury fury;` instead.

**Comment by qinzhikui** [comment]
`private final WeakHashMap<LoaderBinding, Object> allFury = new WeakHashMap();

    public ThreadLocalFury(Function<ClassLoader, Fury> furyFactory) {
        this.bindingThreadLocal = ThreadLocal.withInitial(() -> {
            LoaderBinding binding = new LoaderBinding(furyFactory);
            binding.setBindingCallback(this.factoryCallback);
            binding.setClassLoader(Thread.currentThread().getContextClassLoader());
            this.allFury.put(binding, (Object)null);
            return binding;
        });
        Fury fury = ((LoaderBinding)this.bindingThreadLocal.get()).get();
        ClassResolver._addGraalvmClassRegistry(fury.getConfig().getConfigHash(), fury.getClassResolver());
    }`
It seems that allFury. put() has caused a concurrency conflict

**Comment by chaokunyang** [comment]
Could you provide more details? ThreadLocalFury is created only once, I don't see concurrency conflict

**Comment by qinzhikui** [comment]
This is threadLocal, and each thread will create one. When multiple threads are created simultaneously, they will be put into allFury at the same time

**Comment by chaokunyang** [comment]
I see, thanks. This is indeed a bug, would you like to create a pr?

**Comment by qinzhikui** [comment]
sorry，I am not familiar with using PR. using Collections.synchronizedMap(new WeakHashMap())  or ConcurrentHashMap can solve this problem.
sorry

**Comment by chaokunyang** [comment]
@qinzhikui thanks for your suggestion, I fixed it in https://github.com/apache/fury/pull/1889
