### ISSUE TITLE
[Java] ClassNotCompatibleException even with CompatibleMode.COMPATIBLE

### ISSUE THREAD

**Issue by rvcoutinho** [apache/fury#1864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

OpenJDK 23, Fury 0.7.1, 6.8.0-45-generic #45-Ubuntu.

ClassNotCompatibleException even with CompatibleMode.COMPATIBLE being used.

### Component(s)

Java

### Minimal reproduce step

```
import org.apache.fury.Fury;
import org.apache.fury.config.CompatibleMode;
import org.apache.fury.config.Language;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Serialization test.
 */
public class SerializationTest {

	/** Tests the DTO serialization. */
	@Test
	public void testDtoSerialization() throws Exception {
		final DtoTestObject testObject = new DtoTestObject(1L, "2", "3", 4, new int[] { 5 }, 6);

		final Fury objectSerializer = Fury.builder().registerGuavaTypes(false).withLanguage(Language.XLANG).withCompatibleMode(CompatibleMode.COMPATIBLE)
				.withClassVersionCheck(false).build();
		objectSerializer.register(DtoTestObject.class, DtoTestObject.class.getName());
		final Fury dtoSerializer = Fury.builder().registerGuavaTypes(false).withLanguage(Language.XLANG).withCompatibleMode(CompatibleMode.COMPATIBLE)
				.withClassVersionCheck(false).withDeserializeNonexistentClass(true).build();
		dtoSerializer.register(DtoTestObjectDto.class, DtoTestObject.class.getName());

		// Serializes using general object serializer and de-seralizes using DTO
		// serializer.
		final byte[] serializedObject = objectSerializer.serialize(testObject);
		final DtoTestObjectDto deserializedDto = (DtoTestObjectDto) dtoSerializer.deserialize(serializedObject);
		Assertions.assertEquals(testObject.getId(), deserializedDto.getId());

	}

}

```

### What did you expect to see?

De-serialized object.

### What did you see instead?

ClassNotCompatibleException

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @rvcoutinho , please set language to Java. Xlang doesn't compatible mode yet.

**Comment by rvcoutinho** [comment]
@chaokunyang JAVA does not seem to support XTag. So I cannot serialize/deserealize using different classes with similar schemas. Am I wrong?

**Comment by chaokunyang** [comment]
Short is a big range. You can assign different classes to same id

**Comment by rvcoutinho** [comment]
It does not work on my use case. It would be used to serialize data between applications. Registering would have to be done dynamically. One application cannot manage other applications ids. TypeTag would solve it.

**Comment by chaokunyang** [comment]
I see, thanks. We can update register typetag to make loadClass recognize typetag mapped classes If language is Java, But do not create struct serializer.. I think this will resolve your issue. Would you like to create a pr for it?

**Comment by rvcoutinho** [comment]
I am forking it and will take a look

**Comment by chaokunyang** [comment]
For fury Java serialization, We write full class name instead of type tag, We can take type tag as class name too. Just like Class.getName return type tag
