### ISSUE TITLE
[Question] Python Pypi的包过旧，未支持magic number

### ISSUE THREAD

**Issue by ffgan** [apache/fury#1866]
### Question

pypi的包目前最新的是0.4.1,23年12月发布的，，Go读取py序列化的bytes会报the fury xlang serialization must start with magic number...  。

pyfury在2024.4.20添加了magic number支持，希望能新打包一个版本让pypi的版本跟上

**Comment by chaokunyang** [comment]
We are refactoring pyfury, we may release pyfury in fury 0.9 version
