### ISSUE TITLE
Fury-parent 0.8.0 artifact was not uploaded to Maven central

### ISSUE THREAD

**Issue by juliojgd** [apache/fury#1872]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.8.0

### Component(s)

Java

### Minimal reproduce step

Search at Maven Central: https://central.sonatype.com/artifact/org.apache.fury/fury-parent 

you will find 0.8.0 for fury-core but you won't find 0.8.0 fury-parent.

### What did you expect to see?

0.8.0 for fury-parent present in Maven central

### What did you see instead?

fury-parent 0.8.0 is not present, the latest one is 0.7.1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @juliojgd  does https://repository.apache.org/content/repositories/orgapachefury-1050/ work for you? If it works, I can publish it to maven central now

**Comment by juliojgd** [comment]
Looks good

**Comment by chaokunyang** [comment]
fury-parent pom released now
