### ISSUE TITLE
Scala Optimizations don't support ThreadSafeFury

### ISSUE THREAD

**Issue by davidnadeau** [apache/fury#1894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

0.8.0

### Component(s)

Other

### Minimal reproduce step

```scala
  lazy val fury: ThreadSafeFury = Fury
    .builder()
    .withLanguage(Language.JAVA)
    .withScalaOptimizationEnabled(true)
    .requireClassRegistration(false)
    .withRefTracking(false)
    .buildThreadSafeFuryPool(Runtime.getRuntime.availableProcessors() * 2, Runtime.getRuntime.availableProcessors() * 2)


   ScalaSerializers.registerSerializers(fury)
// Type mismatch
```
![Screenshot 2024-10-21 at 3 26 23 PM](https://github.com/user-attachments/assets/41b43e79-f310-4c3c-87c9-60908a8f20a3)

### What did you expect to see?

Support for ThreadSafeFury.

### What did you see instead?

Compile error.

### Anything Else?

related? https://github.com/apache/fury/issues/1186

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @davidnadeau , I fixed this in #1895 . Currently you can work around it by :
```scala
  lazy val fury: ThreadSafeFury = new ThreadLocalFury(classloader => {
 val furyInstance = Fury
    .builder()
    .withLanguage(Language.JAVA)
    .withScalaOptimizationEnabled(true)
    .requireClassRegistration(false)
    .withClassLoader(classloader)
    .withRefTracking(false)
    .buildThreadSafeFuryPool(Runtime.getRuntime.availableProcessors() * 2, Runtime.getRuntime.availableProcessors() * 2)
   ScalaSerializers.registerSerializers(furyInstance)
   furyInstance
```
