### ISSUE TITLE
[Question] How do I serialize primitive types? 

### ISSUE THREAD

**Issue by dan-ryan** [apache/fury#1900]
### Question

I couldn't see this in the documentation, and maybe this library isn't suited for what I want, but I thought I'd ask just in case.
I'm building an MMO and serializing mostly small chunks of data, but lots of it. Benchmarking my code shows serialization is using a chunk of CPU, so I wanted to see if Fury could improve my performance. 

This is a small example of a byte[] that I'm sending to the client through WebSockets:

```
        try (var byteArrayOutputStream = new ByteArrayOutputStream(1024);
             var dataOutputStream = new DataOutputStream(byteArrayOutputStream)) {
            dataOutputStream.writeByte(SerialisationMethod.Client.PlayerCharacter.ordinal()); // Method type (enum) as a byte
            dataOutputStream.writeUTF(getId()); //GUID string
            return byteArrayOutputStream.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

Can someone give me an example of the best way to write this in Fury?

**Comment by chaokunyang** [comment]
You can just serialize by `fury.serialize(new Object[] {your objects})`. Or you can create a `org.apache.fury.io.MemoryBufferObjectOutput` for that:

```java
MemoryBufferObjectOutput out = new MemoryBufferObjectOutput(fury, buffer);
out.writeByte(SerialisationMethod.Client.PlayerCharacter.ordinal());
out.writeUTF(getId()); //GUID string
byte[] bytes = buffer.getBytes(0, buffer.writerIndex());
buffer.writerIndex(0);
```
