### ISSUE TITLE
[Question] <title> Compatibility

### ISSUE THREAD

**Issue by 92daxia** [apache/fury#1902]
### Question

<img width="850" alt="image" src="https://github.com/user-attachments/assets/c934d4c2-9a9c-43eb-9e2b-fff7535f1f30">
Does this mean that deserialization after property changes in a SomeClass class is incompatible? Or is it incompatible after upgrading Fury?

**Comment by chaokunyang** [comment]
As the document said, Fury supports schema evolution, you can add/remove property in a SomeClass class. But when you upgrade Fury jar from one version to another version, it may be imcompatible
