### ISSUE TITLE
Deserialization creates duplicate instances

### ISSUE THREAD

**Issue by michael-schnell** [apache/fury#1955]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

Fury: 0.9.0 / OS: Windows 11 / JDK 21

### Component(s)

Java

### Minimal reproduce step

Deserialization of two range maps in a container create two different instances of the same object. This leads to increased memory consumption. It is expected that two references to the same object instance will be recreated in the same way they were before serialization (single instance not two).

Attached is a simple Maven project that shows the deserialization problem.

[apache-fury-bug.zip](https://github.com/user-attachments/files/17879048/apache-fury-bug.zip)

### What did you expect to see?

ORIGINAL:
map1: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [2061774051]]
map2: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [2061774051]]

COPY:
map1: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [1990385139]]
map2: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [1990385139]] **// Expected same instance!**

### What did you see instead?

ORIGINAL:
map1: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [2061774051]]
map2: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [2061774051]]

COPY:
map1: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [1990385139]]
map2: [2024-01-01..2024-12-31]=[c0ee7b8d-eab0-4b7e-aeee-6ef2b9d2db8b [1380924218]] **// DIFFERENT INSTANCE!**

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
You should create Fury with reference tracking enabled by `FuryBuilder#withRefTracking`

**Comment by michael-schnell** [comment]
OK. Seems somewhat unexpected that this is not the default.

**Comment by chaokunyang** [comment]
Protobuf/JSON/Flatbuffers doesn't support reference, so Fury disabled it by default
