### ISSUE TITLE
[Question] How to register a custom serializer with ThreadSafeFury?

### ISSUE THREAD

**Issue by michael-schnell** [apache/fury#1965]
### Question

The doc shows how to register a custom serializer: 
https://fury.apache.org/docs/guide/java_object_graph_guide/#implement-a-customized-serializer

```java
Fury fury = getFury();
fury.registerSerializer(Foo.class,new FooSerializer(fury));
```
Unfortunately this approach does not work with a "ThreadSafeFury" instance as all serializer classes expect a "Fury" and not a thread safe instance.

```java
ThreadSafeFury threadSafeFury = getThreadSafeFury();
fury.registerSerializer(Foo.class,new FooSerializer(threadSafeFury)); // Fails as not a "Fury" sub class
```

How do I register a custom serializer with a "ThreadSafeFury" instance?

**Comment by michael-schnell** [comment]
I guess it's like this?
```java
Function<ClassLoader, Fury> furyFactory = cl -> {
    final Fury fury = fury();
    fury.registerSerializer(Foo.class, new FooSerializer(fury));
    return fury;
};
ThreadLocalFury fury = new ThreadLocalFury(furyFactory);
```

**Comment by chaokunyang** [comment]
Yes, you are right. Or you can register serializer by `org.apache.fury.BaseFury#registerSerializer(java.lang.Class<?>, java.util.function.Function<org.apache.fury.Fury,org.apache.fury.serializer.Serializer<?>>)`
